export default[{
   "id":1,
   "name":"苹果手机",
   "type":"electronics",
   "price":10000,
   "imgName":require('@/assets/goods/phone.jpg')
},{
    "id":2,
    "name":"苹果",
    "type":"food",
    "price":10,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/apple.jpg') 
 },{
    "id":3,
    "name":"蛋糕",
    "type":"food",
    "price":100,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/cake.jpg') 
 },{
    "id":4,
    "name":"ThinkPad",
    "type":"electronics",
    "price":20000,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/thinkpad.jpg') 
 },{
    "id":5,
    "name":"冰箱",
    "type":"appliances",
    "price":5000,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/icebox.jpg')
 },{
    "id":6,
    "name":"电视",
    "type":"appliances",
    "price":30000,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/television.jpg')
 },{
    "id":7,
    "name":"奶粉",
    "type":"child",
    "price":100,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/mike.jpg') 
 },{
    "id":8,
    "name":"尿布",
    "type":"child",
    "price":100,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/niaobu.jpg') 
 },{
    "id":9,
    "name":"葡萄酒",
    "type":"drink",
    "price":1000,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/redDrink.jpg') 
 },{
    "id":10,
    "name":"二锅头",
    "type":"drink",
    "price":20,
    "imgName":"phone.jpg",
    "imgName":require('@/assets/goods/erguotou.jpg') 
 }
]